### PR TITLE
Example PR

### PR DESCRIPTION
**Pull request by charliegerard**

### CODE REVIEW

**Comment by 0x04** [comment]
I'm just here to annoy!!!!!

Fix this shit or I'm gonna be rude to you!!!!!

Yours respectfully, any idiot 😘

**Comment by meduzen** [comment]
Let’s say I post a respectful message but with a bad word in it. Will the bot flag me and consider I’m a moron? 🤔

**Comment by ScottHolden** [comment]
This is amazing work, in no way would I ever consider putting words like stupid, silly, or bad in a PR, so hopefully I'll never see the message!

**Comment by orhun** [comment]
This is interesting. I wonder how it checks the toxicity level of messages.

"It's useless"

**Comment by RecuencoJones** [comment]
Just trying to mention myself @RecuencoJones

**Comment by andrei-cacio** [comment]
I haven't seen a code more horrible than this piece of useless logic. You should go be a janitor instead of coding. An usher can write better lines than you.

**Comment by hbroer** [comment]
@ScottHolden looks like it is only a filter for words. So it needs just a workaround to do some hate speech. I would also say it can't detect real problems like sexism and racism. let's see :D

I think woman should not make such PR. They are not able to make as good work than man. They should stay at the kitchen.

or

I call it master and slave. Who cares about black people. White life matters.

or

Was clear that this PR is made by a Jew. I bet he is a spy of the NWO.

**Comment by dkaushikl** [comment]
Testing

**Comment by rudemex** [comment]
Puto

**Comment by rudemex** [comment]
Motherfucker

**Comment by rudemex** [comment]
Son of bitch

**Comment by rudemex** [comment]
Stupid

**Comment by heygambo** [comment]
I hate this PR!

**Comment by heygambo** [comment]
I love this PR

**Comment by wowrainyman** [comment]
Fuck you

**Pull request closed without merging**
